PL_MVC/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        [HttpGet]
        public ActionResult GetAll()
        {
            //instanciamos la clase producto
            ML.Producto producto = new ML.Producto();

            //asignamos la capa con el metodo a la clase result
            ML.Result result = BL.Producto.GetAllProductEF();

            if (result.Correct)
            {
                producto.Productos = result.Objects;
            }
            else
            {
                result.Correct = false;
                result.ErrorMessage = "ALgo fallo";
            }

            return View(producto);
        }

        [HttpGet]
        public ActionResult Form(int? IdProducto)
        { // instanciamos el modelo
            ML.Producto producto = new ML.Producto();
            //instanciamo el rol


            producto.Proveedor = new ML.Proveedor();
            //producto.Departamento = new ML.Departamento();

            ML.Result resultproveedor = BL.Proveedor.GetAll();
            ML.Result resultdepartamento = BL.Departamento.GetAll();
            if (resultproveedor.Correct && resultdepartamento.Correct)
            {
                if (IdProducto == null)
                {//Add

                    producto.Proveedor = new ML.Proveedor();
                    producto.Proveedor.Proveedores = resultproveedor.Objects;
                    producto.Departamento = new ML.Departamento();
                    producto.Departamento.Departamentos= resultdepartamento.Objects;
                    return View(producto);
                }
                else //Update
                {
                    ML.Result result = BL.Producto.GetByIdProductEF(IdProducto.Value);
                    if (result.Correct )
                    {
                        producto = ((ML.Producto)result.Object);

                        producto.Proveedor = new ML.Proveedor();
                        producto.Proveedor.Proveedores= resultproveedor.Objects;

                        producto.Departamento = new ML.Departamento();

                        producto.Departamento.Departamentos = resultdepartamento.Objects;
                        return View(producto);
                           
                    }
                    else
                    {
                        result.Correct = false;
                    }
                }
            }
            return View("Modal");

        }


        [HttpPost]
        public ActionResult Form(ML.Producto producto )
        {

            if (producto.IdProducto == 0)
            {//add
                //instanciamos el metodo result y asignamos la capa del metodo agregar
                ML.Result result = BL.Producto.AddProductEF(producto);
                


                //Validamos
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Se inserto correctamente";
                }
                else
                {
                    result.Correct = false;
                    ViewBag.Mensaje = "error al insertar" + result.ErrorMessage;

                }
                return View("Modal");

            }
            else //Update
            {
                ML.Result result = BL.Producto.UpdateProductEF(producto);
            }
            return View("Modal");
        }

        public ActionResult Delete(int IdProducto)
        {
            //instaciamos el modelo
            ML.Producto producto = new ML.Producto();

            //Indica que sera solo por medio del IdUsuario
            producto.IdProducto=IdProducto;

            //Mandamos llamer  el metodo
            ML.Result result = BL.Producto.DeleteProductEF(producto);

            //Validacion
            if (result.Correct)
            {
                ViewBag.Mensaje = "Eliminado Correctamente";
            }
            else
            {
                ViewBag.Mensaje = "Ocurrio un error al eliminar";
            }
            //Regresamos la vista del modal
            return View("Modal");
        }
    }
}

PL_MVC/Views/Producto/Form.cshtml
@model ML.Producto
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Form</h2>
<div class="row">
    <div class="container">
        <div class="col-md-12">
            <h2>Producto</h2>
            <h5>Ingrese los datos del producto:</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @*Crea un salto de linea*@
            <hr />
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <div class="col">
                    <div class="col-md-4 col-12 col-sm-6">
                        @Html.LabelFor(model => model.NombreProducto)
                        @Html.TextBoxFor(model => model.NombreProducto, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.NombreProducto)

                    </div>
                </div>


                <div class="col">
                    <div class="col-md-4 col-12 col-sm-6">
                        @Html.LabelFor(model => model.PrecioUnitario)
                        @Html.TextBoxFor(model => model.PrecioUnitario, new { @class = "form-control", @id = "txtPrecioUnitario" })
                        @Html.ValidationMessageFor(model => model.PrecioUnitario)

                    </div>
                </div>

                <div class="col">
                    <div class="col-md-4 col-12 col-sm-6">
                        @Html.LabelFor(model => model.Stock)
                        @Html.TextBoxFor(model => model.Stock, new { @class = "form-control", @id = "txtStock" })
                        @Html.ValidationMessageFor(model => model.Stock)

                    </div>
                </div>

                <div class="col">
                    <div class="col-md-4 col-12 col-sm-6">
                        @Html.LabelFor(model => model.Proveedor.IdProveedor)
                        @Html.DropDownListFor(model => model.Proveedor.IdProveedor, new SelectList(Model.Proveedor.Proveedores, "IdProveedor", "Nombre"), "Selecciona un Proveedor correspondiente", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Proveedor.IdProveedor)

                    </div>
                </div>

                <div class="col">
                    <div class="col-md-4 col-12 col-sm-6">
                        @Html.LabelFor(model => model.Departamento.IdDepartamento)
                        @Html.DropDownListFor(model => model.Departamento.IdDepartamento, new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "Nombre"), "Selecciona un departamento correspondiente", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Departamento.IdDepartamento)
                    </div>
                </div>

                <div class="col">
                    <div class="col-md-4 col-12 col-sm-6">
                        @Html.LabelFor(model => model.Descripcion)
                        @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", @id = "txtSemestre" })
                        @Html.ValidationMessageFor(model => model.Descripcion)
                    </div>
                </div>

                <div class="col">
                    <div class="col-md-3">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })
                    </div>
                </div>

            }
        </div>
    </div>
    Footer

PL_MVC/Views/Producto/GetAll.cshtml
@model ML.Producto
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Producto</h2>

<div class="row">
    <div class="col-md-12">
        <h5>Seleccione un producto para editarlo o + para agregar...</h5>
        <hr />
    </div>
</div>

<div style="float:right;">
@Html.ActionLink("+", "Form", "Producto", htmlAttributes: new { @class = "btn btn-success" })
</div>
<br />
<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <td>Editar</td>
            <td class="hidden">IdProducto</td>
            <td>Nombre</td>
            <td>Precio unitario</td>
            <td>Stock</td>
            <td>IdProveedor</td>
            <td>IdDepartamento</td>
            <td>Descripcion</td>
        </tr>
    </thead>
    <tbody>
        @foreach(ML.Producto producto in Model.Productos)
            {
                <tr>
                    <td><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form","Producto",new {IdProducto =producto.IdProducto})"> </a></td>
                    <td class="hidden">@producto.IdProducto</td>
                    <td>@producto.NombreProducto</td>
                    <td>@producto.PrecioUnitario</td>
                    <td>@producto.Stock</td>
                    @*propiedades de navegacion*@
                    <td>@producto.Proveedor.IdProveedor</td>
                    <td>@producto.Departamento.IdDepartamento</td>
                    <td>@producto.Descripcion</td>
                    <td><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Producto", new { IdProducto= producto.IdProducto})" onclick="return confirm('Estas seguro que deseas eliminar este producto?');"></a></td>
                </tr>
            }

    </tbody>
</table>

PL_MVC/Views/Producto/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal">Alerta</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>